/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Stitch "Civic Lumina" design system — monochromatic dark
        "surface-variant":             "#353434",
        "surface-container-lowest":    "#0e0e0e",
        "surface-dim":                 "#141313",
        "on-primary-container":        "#636565",
        "on-primary-fixed-variant":    "#454747",
        "tertiary-fixed":              "#e2e2e2",
        "on-tertiary-fixed":           "#1a1c1c",
        "surface-bright":              "#3a3939",
        "error-container":             "#93000a",
        "on-surface":                  "#e5e2e1",
        "on-background":               "#e5e2e1",
        "tertiary-container":          "#e2e2e2",
        "primary-fixed-dim":           "#c6c6c7",
        "surface-container-high":      "#2a2a2a",
        "primary-container":           "#e2e2e2",
        "tertiary-fixed-dim":          "#c6c6c7",
        "inverse-primary":             "#5d5f5f",
        "surface-container":           "#201f1f",
        "outline":                     "#8e9192",
        "inverse-surface":             "#e5e2e1",
        "on-primary":                  "#2f3131",
        "on-secondary-fixed":          "#171c20",
        "on-error-container":          "#ffdad6",
        "secondary":                   "#c3c7cd",
        "background":                  "#141313",
        "on-tertiary-fixed-variant":   "#454747",
        "outline-variant":             "#444748",
        "on-secondary-fixed-variant":  "#43474c",
        "on-primary-fixed":            "#1a1c1c",
        "on-secondary-container":      "#b4b9bf",
        "on-tertiary":                 "#2f3131",
        "surface":                     "#141313",
        "on-error":                    "#690005",
        "error":                       "#ffb4ab",
        "secondary-fixed":             "#dfe3e9",
        "surface-tint":                "#c6c6c7",
        "on-tertiary-container":       "#636565",
        "on-surface-variant":          "#c4c7c8",
        "primary-fixed":               "#e2e2e2",
        "primary":                     "#ffffff",
        "tertiary":                    "#ffffff",
        "secondary-fixed-dim":         "#c3c7cd",
        "surface-container-highest":   "#353434",
        "secondary-container":         "#454a4f",
        "surface-container-low":       "#1c1b1b",
        "on-secondary":                "#2c3136",
        "inverse-on-surface":          "#313030",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        "2xl":   "1rem",
        "3xl":   "1.5rem",
        full:    "9999px",
      },
      spacing: {
        "margin-mobile":  "16px",
        "container-max":  "1280px",
        "margin-desktop": "64px",
        base:             "8px",
        gutter:           "24px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg":        ["72px",  { lineHeight: "80px",  letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg":       ["48px",  { lineHeight: "56px",  letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile":["32px",  { lineHeight: "40px",  fontWeight: "600" }],
        "headline-md":       ["32px",  { lineHeight: "40px",  fontWeight: "500" }],
        "body-lg":           ["18px",  { lineHeight: "28px",  fontWeight: "400" }],
        "body-md":           ["16px",  { lineHeight: "24px",  fontWeight: "400" }],
        "label-md":          ["14px",  { lineHeight: "20px",  letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm":          ["12px",  { lineHeight: "16px",  letterSpacing: "0.05em", fontWeight: "500" }],
      },
      backdropBlur: {
        xs: "2px",
      },
      animation: {
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
      keyframes: {
        "fade-up": {
          "0%":   { opacity: "0", transform: "translateY(16px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "char-in": {
          "0%":   { opacity: "0", transform: "translateX(-18px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
      },
    },
  },
  plugins: [],
}
