/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "var(--color-surface-variant)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-dim": "var(--color-surface-dim)",
        "on-primary-container": "var(--color-on-primary-container)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "surface-bright": "var(--color-surface-bright)",
        "error-container": "var(--color-error-container)",
        "on-surface": "var(--color-on-surface)",
        "on-background": "var(--color-on-background)",
        "tertiary-container": "var(--color-tertiary-container)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "surface-container-high": "var(--color-surface-container-high)",
        "primary-container": "var(--color-primary-container)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "inverse-primary": "var(--color-inverse-primary)",
        "surface-container": "var(--color-surface-container)",
        "outline": "var(--color-outline)",
        "inverse-surface": "var(--color-inverse-surface)",
        "on-primary": "var(--color-on-primary)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "on-error-container": "var(--color-on-error-container)",
        "secondary": "var(--color-secondary)",
        "background": "var(--color-background)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "outline-variant": "var(--color-outline-variant)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "on-tertiary": "var(--color-on-tertiary)",
        "surface": "var(--color-surface)",
        "on-error": "var(--color-on-error)",
        "error": "var(--color-error)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "surface-tint": "var(--color-surface-tint)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "primary-fixed": "var(--color-primary-fixed)",
        "primary": "var(--color-primary)",
        "tertiary": "var(--color-tertiary)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "secondary-container": "var(--color-secondary-container)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-secondary": "var(--color-on-secondary)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        "2xl":   "1rem",
        "3xl":   "1.5rem",
        full:    "9999px",
      },
      spacing: {
        "margin-mobile":  "16px",
        "container-max":  "1280px",
        "margin-desktop": "64px",
        base:             "8px",
        gutter:           "24px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg":        ["72px",  { lineHeight: "80px",  letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg":       ["48px",  { lineHeight: "56px",  letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile":["32px",  { lineHeight: "40px",  fontWeight: "600" }],
        "headline-md":       ["32px",  { lineHeight: "40px",  fontWeight: "500" }],
        "body-lg":           ["18px",  { lineHeight: "28px",  fontWeight: "400" }],
        "body-md":           ["16px",  { lineHeight: "24px",  fontWeight: "400" }],
        "label-md":          ["14px",  { lineHeight: "20px",  letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm":          ["12px",  { lineHeight: "16px",  letterSpacing: "0.05em", fontWeight: "500" }],
      },
      backdropBlur: {
        xs: "2px",
      },
      animation: {
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
      keyframes: {
        "fade-up": {
          "0%":   { opacity: "0", transform: "translateY(16px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "char-in": {
          "0%":   { opacity: "0", transform: "translateX(-18px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
      },
    },
  },
  plugins: [],
}
